# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from isac/FKsrvRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import isac.msg
import std_msgs.msg

class FKsrvRequest(genpy.Message):
  _md5sum = "758e6b15ca398f922731616dc45a4010"
  _type = "isac/FKsrvRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ArmAngles arm_angles

================================================================================
MSG: isac/ArmAngles
Header header

float32 shoulder
float32 elbow
float32 wrist
float32 gripper
float32 base
float32 wrist_rot
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['arm_angles']
  _slot_types = ['isac/ArmAngles']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm_angles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FKsrvRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm_angles is None:
        self.arm_angles = isac.msg.ArmAngles()
    else:
      self.arm_angles = isac.msg.ArmAngles()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.arm_angles.header.seq, _x.arm_angles.header.stamp.secs, _x.arm_angles.header.stamp.nsecs))
      _x = self.arm_angles.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.arm_angles.shoulder, _x.arm_angles.elbow, _x.arm_angles.wrist, _x.arm_angles.gripper, _x.arm_angles.base, _x.arm_angles.wrist_rot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.arm_angles is None:
        self.arm_angles = isac.msg.ArmAngles()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.arm_angles.header.seq, _x.arm_angles.header.stamp.secs, _x.arm_angles.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.arm_angles.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.arm_angles.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.arm_angles.shoulder, _x.arm_angles.elbow, _x.arm_angles.wrist, _x.arm_angles.gripper, _x.arm_angles.base, _x.arm_angles.wrist_rot,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.arm_angles.header.seq, _x.arm_angles.header.stamp.secs, _x.arm_angles.header.stamp.nsecs))
      _x = self.arm_angles.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.arm_angles.shoulder, _x.arm_angles.elbow, _x.arm_angles.wrist, _x.arm_angles.gripper, _x.arm_angles.base, _x.arm_angles.wrist_rot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.arm_angles is None:
        self.arm_angles = isac.msg.ArmAngles()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.arm_angles.header.seq, _x.arm_angles.header.stamp.secs, _x.arm_angles.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.arm_angles.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.arm_angles.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.arm_angles.shoulder, _x.arm_angles.elbow, _x.arm_angles.wrist, _x.arm_angles.gripper, _x.arm_angles.base, _x.arm_angles.wrist_rot,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from isac/FKsrvResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import isac.msg
import std_msgs.msg

class FKsrvResponse(genpy.Message):
  _md5sum = "bb16a62d4893ddebee7ead2c91bb2a20"
  _type = "isac/FKsrvResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ArmPosition arm_position

================================================================================
MSG: isac/ArmPosition
Header header

float32 x
float32 y
float32 z

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['arm_position']
  _slot_types = ['isac/ArmPosition']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FKsrvResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm_position is None:
        self.arm_position = isac.msg.ArmPosition()
    else:
      self.arm_position = isac.msg.ArmPosition()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.arm_position.header.seq, _x.arm_position.header.stamp.secs, _x.arm_position.header.stamp.nsecs))
      _x = self.arm_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.arm_position.x, _x.arm_position.y, _x.arm_position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.arm_position is None:
        self.arm_position = isac.msg.ArmPosition()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.arm_position.header.seq, _x.arm_position.header.stamp.secs, _x.arm_position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.arm_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.arm_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.arm_position.x, _x.arm_position.y, _x.arm_position.z,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.arm_position.header.seq, _x.arm_position.header.stamp.secs, _x.arm_position.header.stamp.nsecs))
      _x = self.arm_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.arm_position.x, _x.arm_position.y, _x.arm_position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.arm_position is None:
        self.arm_position = isac.msg.ArmPosition()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.arm_position.header.seq, _x.arm_position.header.stamp.secs, _x.arm_position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.arm_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.arm_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.arm_position.x, _x.arm_position.y, _x.arm_position.z,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
class FKsrv(object):
  _type          = 'isac/FKsrv'
  _md5sum = '932b734ed40bf214a466ce1001c6d294'
  _request_class  = FKsrvRequest
  _response_class = FKsrvResponse
