// Generated by gencpp from file isac/arm_angles.msg
// DO NOT EDIT!


#ifndef ISAC_MESSAGE_ARM_ANGLES_H
#define ISAC_MESSAGE_ARM_ANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace isac
{
template <class ContainerAllocator>
struct arm_angles_
{
  typedef arm_angles_<ContainerAllocator> Type;

  arm_angles_()
    : shoulder()
    , elbow()  {
    }
  arm_angles_(const ContainerAllocator& _alloc)
    : shoulder(_alloc)
    , elbow(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shoulder_type;
  _shoulder_type shoulder;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _elbow_type;
  _elbow_type elbow;





  typedef boost::shared_ptr< ::isac::arm_angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::isac::arm_angles_<ContainerAllocator> const> ConstPtr;

}; // struct arm_angles_

typedef ::isac::arm_angles_<std::allocator<void> > arm_angles;

typedef boost::shared_ptr< ::isac::arm_angles > arm_anglesPtr;
typedef boost::shared_ptr< ::isac::arm_angles const> arm_anglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isac::arm_angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::isac::arm_angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace isac

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'isac': ['/home/pawan/Desktop/UD/ROS/ws/rover_ws/src/isac/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::isac::arm_angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::isac::arm_angles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::isac::arm_angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::isac::arm_angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::isac::arm_angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::isac::arm_angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::isac::arm_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "900f93719af8356dfbf506bb017b797f";
  }

  static const char* value(const ::isac::arm_angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x900f93719af8356dULL;
  static const uint64_t static_value2 = 0xfbf506bb017b797fULL;
};

template<class ContainerAllocator>
struct DataType< ::isac::arm_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "isac/arm_angles";
  }

  static const char* value(const ::isac::arm_angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::isac::arm_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string shoulder\n\
string elbow\n\
";
  }

  static const char* value(const ::isac::arm_angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::isac::arm_angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoulder);
      stream.next(m.elbow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::isac::arm_angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::isac::arm_angles_<ContainerAllocator>& v)
  {
    s << indent << "shoulder: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shoulder);
    s << indent << "elbow: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.elbow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISAC_MESSAGE_ARM_ANGLES_H
