// Generated by gencpp from file isac/FKsrvResponse.msg
// DO NOT EDIT!


#ifndef ISAC_MESSAGE_FKSRVRESPONSE_H
#define ISAC_MESSAGE_FKSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <isac/ArmPosition.h>

namespace isac
{
template <class ContainerAllocator>
struct FKsrvResponse_
{
  typedef FKsrvResponse_<ContainerAllocator> Type;

  FKsrvResponse_()
    : arm_position()  {
    }
  FKsrvResponse_(const ContainerAllocator& _alloc)
    : arm_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::isac::ArmPosition_<ContainerAllocator>  _arm_position_type;
  _arm_position_type arm_position;





  typedef boost::shared_ptr< ::isac::FKsrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::isac::FKsrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FKsrvResponse_

typedef ::isac::FKsrvResponse_<std::allocator<void> > FKsrvResponse;

typedef boost::shared_ptr< ::isac::FKsrvResponse > FKsrvResponsePtr;
typedef boost::shared_ptr< ::isac::FKsrvResponse const> FKsrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isac::FKsrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::isac::FKsrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace isac

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'isac': ['/home/pawan/Desktop/UD/ROS/ws/rover_ws/src/isac/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::isac::FKsrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::isac::FKsrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::isac::FKsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::isac::FKsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::isac::FKsrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::isac::FKsrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::isac::FKsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb16a62d4893ddebee7ead2c91bb2a20";
  }

  static const char* value(const ::isac::FKsrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb16a62d4893ddebULL;
  static const uint64_t static_value2 = 0xee7ead2c91bb2a20ULL;
};

template<class ContainerAllocator>
struct DataType< ::isac::FKsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "isac/FKsrvResponse";
  }

  static const char* value(const ::isac::FKsrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::isac::FKsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmPosition arm_position\n\
\n\
================================================================================\n\
MSG: isac/ArmPosition\n\
Header header\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::isac::FKsrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::isac::FKsrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FKsrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::isac::FKsrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::isac::FKsrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "arm_position: ";
    s << std::endl;
    Printer< ::isac::ArmPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.arm_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISAC_MESSAGE_FKSRVRESPONSE_H
