// Generated by gencpp from file isac/IK.msg
// DO NOT EDIT!


#ifndef ISAC_MESSAGE_IK_H
#define ISAC_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <isac/IKRequest.h>
#include <isac/IKResponse.h>


namespace isac
{

struct IK
{

typedef IKRequest Request;
typedef IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IK
} // namespace isac


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::isac::IK > {
  static const char* value()
  {
    return "e04c1b58bd7c12bbba9333174a823636";
  }

  static const char* value(const ::isac::IK&) { return value(); }
};

template<>
struct DataType< ::isac::IK > {
  static const char* value()
  {
    return "isac/IK";
  }

  static const char* value(const ::isac::IK&) { return value(); }
};


// service_traits::MD5Sum< ::isac::IKRequest> should match 
// service_traits::MD5Sum< ::isac::IK > 
template<>
struct MD5Sum< ::isac::IKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::isac::IK >::value();
  }
  static const char* value(const ::isac::IKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::isac::IKRequest> should match 
// service_traits::DataType< ::isac::IK > 
template<>
struct DataType< ::isac::IKRequest>
{
  static const char* value()
  {
    return DataType< ::isac::IK >::value();
  }
  static const char* value(const ::isac::IKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::isac::IKResponse> should match 
// service_traits::MD5Sum< ::isac::IK > 
template<>
struct MD5Sum< ::isac::IKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::isac::IK >::value();
  }
  static const char* value(const ::isac::IKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::isac::IKResponse> should match 
// service_traits::DataType< ::isac::IK > 
template<>
struct DataType< ::isac::IKResponse>
{
  static const char* value()
  {
    return DataType< ::isac::IK >::value();
  }
  static const char* value(const ::isac::IKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISAC_MESSAGE_IK_H
