// Generated by gencpp from file isac/IKsrv.msg
// DO NOT EDIT!


#ifndef ISAC_MESSAGE_IKSRV_H
#define ISAC_MESSAGE_IKSRV_H

#include <ros/service_traits.h>


#include <isac/IKsrvRequest.h>
#include <isac/IKsrvResponse.h>


namespace isac
{

struct IKsrv
{

typedef IKsrvRequest Request;
typedef IKsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKsrv
} // namespace isac


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::isac::IKsrv > {
  static const char* value()
  {
    return "e04c1b58bd7c12bbba9333174a823636";
  }

  static const char* value(const ::isac::IKsrv&) { return value(); }
};

template<>
struct DataType< ::isac::IKsrv > {
  static const char* value()
  {
    return "isac/IKsrv";
  }

  static const char* value(const ::isac::IKsrv&) { return value(); }
};


// service_traits::MD5Sum< ::isac::IKsrvRequest> should match 
// service_traits::MD5Sum< ::isac::IKsrv > 
template<>
struct MD5Sum< ::isac::IKsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::isac::IKsrv >::value();
  }
  static const char* value(const ::isac::IKsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::isac::IKsrvRequest> should match 
// service_traits::DataType< ::isac::IKsrv > 
template<>
struct DataType< ::isac::IKsrvRequest>
{
  static const char* value()
  {
    return DataType< ::isac::IKsrv >::value();
  }
  static const char* value(const ::isac::IKsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::isac::IKsrvResponse> should match 
// service_traits::MD5Sum< ::isac::IKsrv > 
template<>
struct MD5Sum< ::isac::IKsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::isac::IKsrv >::value();
  }
  static const char* value(const ::isac::IKsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::isac::IKsrvResponse> should match 
// service_traits::DataType< ::isac::IKsrv > 
template<>
struct DataType< ::isac::IKsrvResponse>
{
  static const char* value()
  {
    return DataType< ::isac::IKsrv >::value();
  }
  static const char* value(const ::isac::IKsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ISAC_MESSAGE_IKSRV_H
